---
title: "edld610_lab5"
author: "Cameron Kay and Ashley Miller"
date: "2/13/2019"
output: html_document
---

```{r setup, include=FALSE}
# load packages
library(tidyverse)
library(magrittr)
library(rio)
library(here)
library(ggrepel)

# import and tidy column names
states_data <- import(here("data/states_all.csv"), setclass = "tibble") %>%
  janitor::clean_names()

```

```{r part1_ash}

```

```{r part2_cam, fig.width = 12, fig.asp = .4}
# prepare data
cam_data <- states_data %>%
  mutate(rev_enr = total_revenue / enroll) %>%
  group_by(state) %>%
  summarize(avg_revenue = mean(rev_enr,             na.rm = TRUE),
            avg_math    = mean(avg_math_8_score,    na.rm = TRUE),
            avg_reading = mean(avg_reading_8_score, na.rm = TRUE)) %>%
  filter(!is.na(avg_revenue),
         !is.na(avg_math),
         !is.na(avg_reading)) %>%
  gather(key   = "content",
         value = "avg_score",
         avg_math:avg_reading) %>%
  mutate(content = gsub("avg_", "", content),
         content = stringr::str_to_title(content),
         state   = gsub("_", " ", state),
         state   = stringr::str_to_title(state),
         state   = gsub("Of", "of", state)) %>%
  arrange(state)

# reproduce plot
ggplot(cam_data, aes(x = avg_revenue, y = avg_score)) +
  geom_point() +
  facet_wrap(~content) +
  theme_minimal()

# improve plot
ggplot(cam_data, aes(x = avg_revenue, y = avg_score)) +
  geom_point(alpha = .4, color = "#f72257", size = 3) +
  facet_wrap(~content) +
  geom_point(data = slice(arrange(cam_data, desc(avg_revenue)), 1:10),
             color = "#6400a3", size = 3) +
  geom_text_repel(data  = slice(arrange(cam_data, desc(avg_revenue)), 1:10),
                aes(label = state), size = 6,
              min.segment.length = 0) +
  geom_point(data = slice(arrange(cam_data, avg_revenue), 1:10),
             color = "#00a9ff", size = 3) +
  geom_text_repel(data  = slice(arrange(cam_data, avg_revenue), 1:10),
              aes(label = state), size = 6,
              min.segment.length = 0) +
  scale_x_continuous(labels = scales::dollar) +
  labs(title = "Math and reading scores and state revenue per student",
       y = "Score",
       x = "State revenue per student",
       caption = "Data from www.kaggle.com/noriuk/us-education-datasets-unification-project") +
  theme_bw() +
  theme(title = element_text(face = "bold", size = 15),
        axis.title.x = element_text(face = "bold", size = 15),
        axis.title.y = element_text(face = "bold", size = 15),
        strip.background = element_rect(fill = "black"),
        strip.text = element_text(face = "bold", color = "white", size = 15),
        axis.text = element_text(size = 15)
        )
  



```
